---
# tasks file for doudou.autoproj-jenkins
- name: "install autoproj-required jenkins plugins"
  include_role:
      allow_duplicates: true
      name: geerlingguy.jenkins
      tasks_from: plugins.yml 
  vars:
      jenkins_plugins: "{{ autoproj_required_jenkins_plugins }}"
- name: "setup sudo for autoproj under jenkins"
  include: "sudo.yml"
- name: "install required supporting packages"
  include: "packages.yml"

